# Override ścieżek dla docker-compose (automatycznie generowany)
# Data: Mon Mar 23 09:34:27 CET 2026
# EDYTUJ SETUP-DOCKER.SH, A NIE TEN PLIK

services:
  postgres:
    volumes:
      - /home/radkos/data_server/data/postgres_data:/var/lib/postgresql/data
  
  redis:
    volumes:
      - /home/radkos/data_server/data/redis_data:/data
  
  app:
    volumes:
      - /home/radkos/data_server/data/imports_input:/data/imports_input
      - ./data/app_logs:/app/logs
